# Site settings
remote_theme: chesterhow/tale
title:          Sleep is my life
description:    "Study summary place"
baseurl:        ""
url:            "https://sleepyjun.github.io"
# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         sleepyjun
  url:          https://sleepyjun.github.io
  email:        sestrik@naver.com

# Build settings
markdown:       kramdown
highlighter: 		rouge
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
	- jekyll-remote-theme
	
# Permalinks
permalink:      /:categories/:title #/:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
